#import <PEGKit/PKParser.h>

enum {
    MISQUERYPARSER_TOKEN_KIND_TRUE = 14,
    MISQUERYPARSER_TOKEN_KIND_GE_SYM = 15,
    MISQUERYPARSER_TOKEN_KIND_DOUBLE_AMPERSAND = 16,
    MISQUERYPARSER_TOKEN_KIND_LIKE = 17,
    MISQUERYPARSER_TOKEN_KIND_LT = 18,
    MISQUERYPARSER_TOKEN_KIND_NOT_EQUAL = 19,
    MISQUERYPARSER_TOKEN_KIND_AND_UPPER = 20,
    MISQUERYPARSER_TOKEN_KIND_EQUALS = 21,
    MISQUERYPARSER_TOKEN_KIND_ENDSWITH = 22,
    MISQUERYPARSER_TOKEN_KIND_BANG = 23,
    MISQUERYPARSER_TOKEN_KIND_GT = 24,
    MISQUERYPARSER_TOKEN_KIND_LE_SYM = 25,
    MISQUERYPARSER_TOKEN_KIND_NOT_UPPER = 26,
    MISQUERYPARSER_TOKEN_KIND_OR_UPPER = 27,
    MISQUERYPARSER_TOKEN_KIND_FALSE = 28,
    MISQUERYPARSER_TOKEN_KIND_BEGINSWITH = 29,
    MISQUERYPARSER_TOKEN_KIND_NOT_EQUALS = 30,
    MISQUERYPARSER_TOKEN_KIND_CONTAINS = 31,
    MISQUERYPARSER_TOKEN_KIND_EL_SYM = 32,
    MISQUERYPARSER_TOKEN_KIND_MATCHES = 33,
    MISQUERYPARSER_TOKEN_KIND_OPEN_PAREN = 34,
    MISQUERYPARSER_TOKEN_KIND_DOUBLE_EQUALS = 35,
    MISQUERYPARSER_TOKEN_KIND_CLOSE_PAREN = 36,
    MISQUERYPARSER_TOKEN_KIND_HASH_ROCKET = 37,
    MISQUERYPARSER_TOKEN_KIND_DOUBLE_PIPE = 38,
};

@interface MISQueryParser : PKParser

@end

